FROM php:7.2.34-fpm-alpine3.12

RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache libstdc++ openssl bash c-ares-dev vim supervisor \
    && apk add --no-cache --virtual .build-deps autoconf dpkg-dev dpkg file g++ gcc libc-dev make \
    && apk add --no-cache libmcrypt-dev \
    && pecl channel-update pecl.php.net \
    && MAKEFLAGS="-j $(nproc)" pecl install mcrypt redis \
    && docker-php-ext-enable mcrypt redis  \
    && apk add --no-cache libzip-dev libxml2-dev libxslt-dev \
    && docker-php-ext-install -j$(nproc) \
    mysqli \
    mbstring \
    pdo \
    pdo_mysql \
    xml \
    pcntl \
    bcmath \
    zip \
    sockets \
    xsl  \
    && apk add --no-cache libjpeg-turbo-dev libpng-dev gd-dev libx11-dev libxpm-dev freetype-dev zlib-dev \
    && docker-php-ext-configure gd --with-gd=/usr/ --with-freetype-dir=/usr/ --with-jpeg-dir=/usr/ --with-png-dir=/usr/ --with-zlib-dir=/usr/ --with-xpm-dir=/usr/ \
    && docker-php-ext-install -j$(nproc) gd \
    && apk del .build-deps \
    && rm -rf /tmp/pear \
    && rm -rf /var/cache/apk/* /tmp/* /usr/share/man 