ARG BASE_IMAGE=dmcz0/php:8.4-dev-debian-13-swoole-6.1.5

FROM ${BASE_IMAGE}

ARG GRPC_VERSION=1.76.0

RUN set -eux; \
    cd /tmp; \
    git clone -b "v${GRPC_VERSION}" --recurse-submodules https://github.com/grpc/grpc; \
    cd /tmp/grpc; \
    # protoc + grpc_php_plugin
    mkdir -p cmake/build; \
    cd cmake/build; \
    cmake ../.. \
      -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local; \
    cmake --build . -j"$(nproc)"; \
    cmake --install .; \
    ldconfig; \
    # PHP extension
    cd /tmp/grpc/src/php/ext/grpc; \
    phpize; \
    ./configure; \
    make -j"$(nproc)"; \
    make install; \
    echo "extension=grpc.so" > "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d/50_grpc.ini"; \
    echo "grpc.enable_fork_support = 1" >> "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d/50_grpc.ini"; \
    rm -rf /tmp/*
