FROM php:8.0-fpm-alpine3.16
LABEL author="dmcz"

# 换aliyun的源后 zlib-dev安装会报签名校验异常
RUN apk add --update --no-cache zlib-dev icu-dev libpng libpng-dev diffutils imagemagick \
    && apk add --update --no-cache --virtual .build-dependencies $PHPIZE_DEPS \
    && docker-php-ext-configure intl \ 
    && docker-php-ext-install mysqli pdo pdo_mysql intl gd \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && pecl clear-cache \
    && apk del .build-dependencies