ARG DEBIAN_VERSION=13

FROM debian:${DEBIAN_VERSION}

LABEL maintainer="Dmcz <751662789@163.com>" version="1.0" license="MIT"

ARG PHP_VERSION_MAJOR=8
ARG PHP_VERSION_MINOR=4
ARG PHP_VERSION_PATCH=0
ARG ZTS_SUFFIX=
ARG TZ=Asia/Shanghai

ENV TZ=${TZ}
ENV PHP_VERSION=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}.${PHP_VERSION_PATCH}
ENV PHP_VERSION_SHORT=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}

RUN set -eux; \
    apt-get update; \
    # 必要的库
    apt-get install -y --no-install-recommends \
    tzdata \
    ca-certificates \
    curl \
    lsb-release \
    libcurl4-openssl-dev \
    pkg-config \
    libc-ares-dev \
    g++ \
    cpp \
    autoconf \
    automake \
    make \
    cmake \
    libtool \
    ; \
    # 开发中可能会用到的库
    apt-get install -y --no-install-recommends \
    vim wget zip unzip git net-tools iputils-ping \
    ; \
    # 时区
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime; \
    echo $TZ > /etc/timezone; \
    # php源
    curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb; \
    dpkg -i /tmp/debsuryorg-archive-keyring.deb; \
    sh -c 'echo "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'; \
    apt-get update; \
    rm -rf /tmp/*; \
    rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
    apt-get update; \
    apt-get --no-install-recommends install -y \
    php${PHP_VERSION_SHORT}-cli \
    php${PHP_VERSION_SHORT}-dev \
    php${PHP_VERSION_SHORT}-common \
    php${PHP_VERSION_SHORT}-bcmath \
    php${PHP_VERSION_SHORT}-curl \
    php${PHP_VERSION_SHORT}-ctype \
    php${PHP_VERSION_SHORT}-dom \
    php${PHP_VERSION_SHORT}-fileinfo \
    php${PHP_VERSION_SHORT}-gd \
    php${PHP_VERSION_SHORT}-iconv \
    php${PHP_VERSION_SHORT}-mbstring \
    php${PHP_VERSION_SHORT}-mysqlnd \
    php${PHP_VERSION_SHORT}-pdo \
    php${PHP_VERSION_SHORT}-phar \
    php${PHP_VERSION_SHORT}-posix \
    php${PHP_VERSION_SHORT}-redis \
    php${PHP_VERSION_SHORT}-sockets \
    php${PHP_VERSION_SHORT}-sysvshm \
    php${PHP_VERSION_SHORT}-sysvmsg \
    php${PHP_VERSION_SHORT}-sysvsem \
    php${PHP_VERSION_SHORT}-simplexml \
    php${PHP_VERSION_SHORT}-tokenizer \
    php${PHP_VERSION_SHORT}-zip \
    php${PHP_VERSION_SHORT}-xml \
    php${PHP_VERSION_SHORT}-xmlreader \
    php${PHP_VERSION_SHORT}-xmlwriter \
    php${PHP_VERSION_SHORT}-opcache \
    ; \
    ## 安装composer
    curl -sSLo /tmp/composer-setup.php https://getcomposer.org/installer; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/*
