ARG DEBIAN_VERSION=13

FROM debian:${DEBIAN_VERSION}

LABEL maintainer="Dmcz <751662789@163.com>" version="1.0" license="MIT"

ARG PHP_VERSION_MAJOR=8
ARG PHP_VERSION_MINOR=4
ARG PHP_VERSION_PATCH=0
ARG PHP_ZTS=0
ARG TZ=Asia/Shanghai
ARG MAKEFLAGS="-j$(nproc)"

ENV TZ=${TZ}
ENV PHP_VERSION=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}.${PHP_VERSION_PATCH}
ENV PHP_VERSION_SHORT=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV MAKEFLAGS="${MAKEFLAGS}"

RUN set -eux; \
    apt-get update; \
    # Build dependencies
    apt-get install -y --no-install-recommends \
    tzdata \
    ca-certificates \
    curl \
    pkg-config \
    libcurl4-openssl-dev \
    libc-ares-dev \
    g++ \
    cpp \
    autoconf \
    automake \
    make \
    cmake \
    libtool \
    bison \
    re2c \
    libssl-dev \
    libxml2-dev \
    libsqlite3-dev \
    libonig-dev \
    libzip-dev \
    zlib1g-dev \
    libreadline-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    libzstd-dev \
    liblz4-dev \
    liblzf-dev \
    ; \
    # Common tools
    apt-get install -y --no-install-recommends \
    vim wget zip unzip openssh-client git net-tools iputils-ping \
    ; \
    # Timezone
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime; \
    echo $TZ > /etc/timezone; \
    rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
    cd /tmp; \
    curl -sSLo php.tar.gz "https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz"; \
    tar -xf php.tar.gz; \
    cd "php-${PHP_VERSION}"; \
    PHP_ZTS_ARG=""; \
    if [ "${PHP_ZTS}" = "1" ]; then \
        PHP_ZTS_ARG="--enable-zts"; \
    fi; \
    ./configure \
      --prefix=/usr/local/php \
      --with-config-file-path="/etc/php/${PHP_VERSION_SHORT}/cli" \
      --with-config-file-scan-dir="/etc/php/${PHP_VERSION_SHORT}/cli/conf.d" \
      ${PHP_ZTS_ARG} \
      --enable-bcmath \
      --enable-exif \
      --enable-gd \
      --enable-intl \
      --enable-mbstring \
      --enable-opcache \
      --enable-pdo \
      --enable-pcntl \
      --enable-posix \
      --enable-sockets \
      --enable-soap \
      --enable-sysvmsg \
      --enable-sysvsem \
      --enable-sysvshm \
      --with-curl \
      --with-freetype \
      --with-gettext \
      --with-iconv \
      --with-jpeg \
      --with-mysqli=mysqlnd \
      --with-openssl \
      --with-pdo-mysql=mysqlnd \
      --with-readline \
      --with-zip \
      --with-zlib \
      --with-pear \
      ; \
    make; \
    make install; \
    mkdir -p "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d"; \
    cp php.ini-production "/etc/php/${PHP_VERSION_SHORT}/cli/php.ini"; \
    ln -s /usr/local/php/bin/php /usr/local/bin/php; \
    ln -s /usr/local/php/bin/phpize /usr/local/bin/phpize; \
    ln -s /usr/local/php/bin/php-config /usr/local/bin/php-config; \
    ln -s /usr/local/php/bin/pecl /usr/local/bin/pecl; \
    ln -s /usr/local/php/bin/pear /usr/local/bin/pear; \
    rm -rf /tmp/*;

RUN set -eux; \
    pecl channel-update pecl.php.net; \
    # 先装 igbinary（redis 会用到）
    pecl install -n igbinary; \
    pecl install -n --configureoptions=' enable-redis-igbinary="yes" enable-redis-zstd="yes" enable-redis-lz4="yes" enable-redis-lzf="yes" ' redis; \
    echo "extension=redis.so" > "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d/redis.ini"; \
    echo "extension=igbinary.so" > "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d/igbinary.ini"; \
    # Install composer
    curl -sSLo /tmp/composer-setup.php https://getcomposer.org/installer; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/; \
    rm -rf /tmp/*;
