ARG DEBIAN_VERSION=13

FROM debian:${DEBIAN_VERSION}

LABEL maintainer="Dmcz <751662789@163.com>" version="1.0" license="MIT"

ARG PHP_VERSION_MAJOR=8
ARG PHP_VERSION_MINOR=4
ARG PHP_VERSION_PATCH=0
ARG TZ=Asia/Shanghai

ENV TZ=${TZ}
ENV PHP_VERSION=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}.${PHP_VERSION_PATCH}
ENV PHP_VERSION_SHORT=${PHP_VERSION_MAJOR}.${PHP_VERSION_MINOR}

RUN set -eux; \
    apt-get update; \
    # 必要的库
    apt-get install -y --no-install-recommends \
    tzdata \
    ca-certificates \
    curl \
    lsb-release \
    pkg-config \
    g++ \
    cpp \
    autoconf \
    automake \
    make \
    cmake \
    libtool \
    bison \
    re2c \
    libcurl4-openssl-dev \
    libc-ares-dev \
    libssl-dev \
    libxml2-dev \
    libsqlite3-dev \
    libonig-dev \
    libzip-dev \
    zlib1g-dev \
    libreadline-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    ; \
    # 开发中可能会用到的库
    apt-get install -y --no-install-recommends \
    vim wget zip unzip git net-tools iputils-ping \
    ; \
    # 时区
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime; \
    echo $TZ > /etc/timezone; \
    rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
    cd /tmp; \
    curl -sSLo php.tar.gz "https://www.php.net/distributions/php-${PHP_VERSION}.tar.gz"; \
    tar -xf php.tar.gz; \
    cd "php-${PHP_VERSION}"; \
    ./configure \
      --prefix=/usr/local/php \
      --with-config-file-path="/etc/php/${PHP_VERSION_SHORT}/cli" \
      --with-config-file-scan-dir="/etc/php/${PHP_VERSION_SHORT}/cli/conf.d" \
      --enable-zts \
      --enable-bcmath \
      --enable-exif \
      --enable-fpm \
      --enable-gd \
      --enable-intl \
      --enable-mbstring \
      --enable-opcache \
      --enable-pcntl \
      --enable-posix \
      --enable-sockets \
      --enable-soap \
      --enable-sysvmsg \
      --enable-sysvsem \
      --enable-sysvshm \
      --with-curl \
      --with-freetype \
      --with-gettext \
      --with-iconv \
      --with-jpeg \
      --with-mysqli=mysqlnd \
      --with-openssl \
      --with-pdo-mysql=mysqlnd \
      --with-readline \
      --with-zip \
      --with-zlib \
      --with-pear \
      ; \
    make -j"$(nproc)"; \
    make install; \
    mkdir -p "/etc/php/${PHP_VERSION_SHORT}/cli/conf.d"; \
    cp php.ini-production "/etc/php/${PHP_VERSION_SHORT}/cli/php.ini"; \
    ln -s /usr/local/php/bin/php /usr/local/bin/php; \
    ln -s /usr/local/php/bin/phpize /usr/local/bin/phpize; \
    ln -s /usr/local/php/bin/php-config /usr/local/bin/php-config; \
    ln -s /usr/local/php/bin/pecl /usr/local/bin/pecl; \
    ln -s /usr/local/php/bin/pear /usr/local/bin/pear; \
    rm -rf /tmp/*;

RUN set -eux; \
    # 安装composer
    curl -sSLo /tmp/composer-setup.php https://getcomposer.org/installer; \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/; \
    rm -rf /tmp/*
