ARG BASE_IMAGE=dmcz0/php:8.4-dev-debian-13

FROM ${BASE_IMAGE}

ARG SWOOLE_VERSION=6.1.5
ARG SWOOLE_THREAD=0
ARG MAKEFLAGS="-j$(nproc)"
ENV MAKEFLAGS="${MAKEFLAGS}"

RUN set -eux; \
    cd /tmp; \
    curl -SL "https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz" -o swoole.tar.gz; \
    mkdir -p swoole; \
    tar -xf swoole.tar.gz -C swoole --strip-components=1; \
    cd swoole; \
    phpize; \
    SWOOLE_CONFIGURE_ARGS="--enable-openssl --enable-swoole-curl --enable-cares"; \
    if [ "${SWOOLE_THREAD}" = "1" ]; then \
        SWOOLE_CONFIGURE_ARGS="${SWOOLE_CONFIGURE_ARGS} --enable-swoole-thread"; \
    fi; \
    ./configure ${SWOOLE_CONFIGURE_ARGS}; \
    make -s && make install; \
    echo "memory_limit=1G" > /etc/php/${PHP_VERSION_SHORT}/cli/conf.d/00_default.ini; \
    echo "opcache.enable_cli = 'On'" >> /etc/php/${PHP_VERSION_SHORT}/cli/conf.d/00_opcache.ini; \
    echo "extension=swoole.so" > /etc/php/${PHP_VERSION_SHORT}/cli/conf.d/50_swoole.ini; \
    echo "swoole.use_shortname = 'Off'" >> /etc/php/${PHP_VERSION_SHORT}/cli/conf.d/50_swoole.ini; \
    rm -rf /tmp/* ;
