ARG DEBIAN_VERSION=13
ARG PHP_VERSION=8.4

FROM dmcz0/php:${PHP_VERSION}-dev-debian-${DEBIAN_VERSION}

ARG PHP_VERSION
ARG SWOOLE_VERSION=6.1.5

RUN set -eux; \
    cd /tmp; \
    curl -SL "https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz" -o swoole.tar.gz; \
    mkdir -p swoole; \
    tar -xf swoole.tar.gz -C swoole --strip-components=1; \
    cd swoole; \
    phpize; \
    ./configure --enable-openssl --enable-swoole-curl --enable-cares; \
    make -s -j$(nproc) && make install; \
    echo "memory_limit=1G" > /etc/php/${PHP_VERSION}/cli/conf.d/00_default.ini; \
    echo "opcache.enable_cli = 'On'" >> /etc/php/${PHP_VERSION}/cli/conf.d/00_opcache.ini; \
    echo "extension=swoole.so" > /etc/php/${PHP_VERSION}/cli/conf.d/50_swoole.ini; \
    echo "swoole.use_shortname = 'Off'" >> /etc/php/${PHP_VERSION}/cli/conf.d/50_swoole.ini; \
    rm -rf /tmp/* ;