ARG UBUNTU_VERSION=22.04
ARG PHP_VERSION=8.2
ARG SWOOLE_VERSION=5.1.0

FROM dmcz0/php:${PHP_VERSION}-dev-ubuntu-${UBUNTU_VERSION}-swoole-${SWOOLE_VERSION}

ARG GRPC_VERSION=1.59.1

RUN set -ex \
    && MAKEFLAGS="-j $(nproc)" pecl install grpc-${GRPC_VERSION} \
    && echo "extension=grpc.so" > /etc/php/${PHP_VERSION}/cli/conf.d/50_grpc.ini \
    && echo "grpc.enable_fork_support = 1" >> /etc/php/${PHP_VERSION}/cli/conf.d/50_grpc.ini \ 
    # download & init grpc repo
    && cd /tmp \
    && git clone -b v${GRPC_VERSION} https://github.com/grpc/grpc \
    && cd grpc \
    && git submodule update --init \
    # build & install Grpc C core library , protoc , protpc plugin
    && mkdir -p cmake/build && cd cmake/build \
    && cmake ../.. \
    && make -s -j$(nproc) protoc grpc_php_plugin && make install -s -j$(nproc) protoc grpc_php_plugin \
    # share lib
    && ldconfig \
    # clean
    &&  rm -rf /tmp/*